// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/table/v1/table.proto

package table

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Guest         string                 `protobuf:"bytes,2,opt,name=guest,proto3" json:"guest,omitempty"`
	Seat          int32                  `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`
	BuyInAmount   int64                  `protobuf:"varint,4,opt,name=buyInAmount,proto3" json:"buyInAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTableRequest) Reset() {
	*x = JoinTableRequest{}
	mi := &file_proto_table_v1_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTableRequest) ProtoMessage() {}

func (x *JoinTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_v1_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTableRequest.ProtoReflect.Descriptor instead.
func (*JoinTableRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_v1_table_proto_rawDescGZIP(), []int{0}
}

func (x *JoinTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *JoinTableRequest) GetGuest() string {
	if x != nil {
		return x.Guest
	}
	return ""
}

func (x *JoinTableRequest) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *JoinTableRequest) GetBuyInAmount() int64 {
	if x != nil {
		return x.BuyInAmount
	}
	return 0
}

type JoinTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTableResponse) Reset() {
	*x = JoinTableResponse{}
	mi := &file_proto_table_v1_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTableResponse) ProtoMessage() {}

func (x *JoinTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_v1_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTableResponse.ProtoReflect.Descriptor instead.
func (*JoinTableResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_v1_table_proto_rawDescGZIP(), []int{1}
}

func (x *JoinTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinTableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_table_v1_table_proto protoreflect.FileDescriptor

const file_proto_table_v1_table_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/table/v1/table.proto\x12\x05table\"y\n" +
	"\x10JoinTableRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x14\n" +
	"\x05guest\x18\x02 \x01(\tR\x05guest\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\x05R\x04seat\x12 \n" +
	"\vbuyInAmount\x18\x04 \x01(\x03R\vbuyInAmount\"]\n" +
	"\x11JoinTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2N\n" +
	"\fTableService\x12>\n" +
	"\tJoinTable\x12\x17.table.JoinTableRequest\x1a\x18.table.JoinTableResponseBR\n" +
	"#com.HeadsUpMastersV2.proto.table.v1B\n" +
	"TableProtoP\x01Z\x1dGoServer/proto/table/v1;tableb\x06proto3"

var (
	file_proto_table_v1_table_proto_rawDescOnce sync.Once
	file_proto_table_v1_table_proto_rawDescData []byte
)

func file_proto_table_v1_table_proto_rawDescGZIP() []byte {
	file_proto_table_v1_table_proto_rawDescOnce.Do(func() {
		file_proto_table_v1_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_table_v1_table_proto_rawDesc), len(file_proto_table_v1_table_proto_rawDesc)))
	})
	return file_proto_table_v1_table_proto_rawDescData
}

var file_proto_table_v1_table_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_table_v1_table_proto_goTypes = []any{
	(*JoinTableRequest)(nil),  // 0: table.JoinTableRequest
	(*JoinTableResponse)(nil), // 1: table.JoinTableResponse
}
var file_proto_table_v1_table_proto_depIdxs = []int32{
	0, // 0: table.TableService.JoinTable:input_type -> table.JoinTableRequest
	1, // 1: table.TableService.JoinTable:output_type -> table.JoinTableResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_table_v1_table_proto_init() }
func file_proto_table_v1_table_proto_init() {
	if File_proto_table_v1_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_table_v1_table_proto_rawDesc), len(file_proto_table_v1_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_table_v1_table_proto_goTypes,
		DependencyIndexes: file_proto_table_v1_table_proto_depIdxs,
		MessageInfos:      file_proto_table_v1_table_proto_msgTypes,
	}.Build()
	File_proto_table_v1_table_proto = out.File
	file_proto_table_v1_table_proto_goTypes = nil
	file_proto_table_v1_table_proto_depIdxs = nil
}
